env:
  - CODECOV_TOKEN="b8871147-b00a-45c2-b064-bbe776887a94"

language: python

python:
  - "3.4"

install:
  - pip install -U pip setuptools coverage pytest codecov pytest-cov
  - python setup.py develop

script:
  - pytest --cov=./
  - codecov
